version: '3'
services:
  mongo:
    image: mongo:4.4
    command: --replSet rs0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db

  ldap:
    image: bitnami/openldap:latest
    stdin_open: true
    tty: true
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
  eln:
    image: mylims/new-eln-server
    ports:
      - 3333:3333
    volumes:
      - D:\Zakodium\docker-eln-volumes\addons:/usr/mylims/addons
      - D:\Zakodium\docker-eln-volumes\config:/usr/mylims/config
volumes:
  mongo-data:
