version: '3'
services:
  mongo:
    image: mongo:4.4
    command: --replSet rs0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db

  mongoInit:
    image: mongo
    links:
      - mongo
    volumes:
      - ./production:/production
    command:
      - /production/init-db.sh
    depends_on:
      - mongo

  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - '3333:3333'
    init: true
    volumes:
      - ./production/config.json:/usr/mylims/app/config.json
      - ./.env.prod:/usr/mylims/.env

  command-sync:
    build: .
    command: ['node', 'ace', 'file:sync']
    depends_on:
      - mongo
      - backend
    volumes:
      - ./production/config.json:/usr/mylims/app/config.json
      - ./.env.prod:/usr/mylims/.env

  command-import:
    build: .
    command: ['node', 'ace', 'file:import']
    depends_on:
      - mongo
      - backend
    volumes:
      - ./production/config.json:/usr/mylims/app/config.json
      - ./.env.prod:/usr/mylims/.env

  frontend:
    build: ./front
    depends_on:
      - backend
    ports:
      - '3000:80'
    environment:
      - VITE_PUBLIC_API_URL=http://backend:3333

  proxy:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./production/proxy.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-data:
