version: '3'
services:
  mongo:
    image: mongo:4.4
    command: --replSet rs0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db
  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - ADMIN_PASSWORD=zakodium
      - LOG_LEVEL=debug
      - BACKEND_URL=http://localhost:8080/api
      - FRONTEND_URL=http://localhost:8080
  frontend:
    build: ./front
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
  proxy:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
volumes:
  mongo-data:
