version: '3'
services:
  mongo:
    image: mongo:4.4
    command: --replSet rs0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db
  openldap:
    image: bitnami/openldap:latest
    ports:
      - 1389:1389
      - 1636:1636
volumes:
  mongo-data: