version: '3'
services:
  mongo:
    image: mongo:4.4
    command: --replSet rs0
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - mongo-data:/data/db

  mongoInit:
    image: mongo
    links:
      - mongo
    volumes:
      - ./production:/production
    command:
      - /production/init-db.sh
    depends_on:
      - mongo

  backend:
    build: .
    depends_on:
      - mongo
    ports:
      - '3333:3333'
    environment:
      - PORT=3333
      - HOST=0.0.0.0
      - NODE_ENV=production
      - ADMIN_PASSWORD=zakodium
      - LOG_LEVEL=info
      - BACKEND_URL=http://127.0.0.1:3333
      - FRONTEND_URL=http://frontend:3000
      - DRIVE_DISK=local
      - DRIVE_ROOT=files

  frontend:
    build: ./front
    depends_on:
      - backend
    ports:
      - '3000:80'
    environment:
      - VITE_PUBLIC_API_URL=http://backend:3333

  proxy:
    image: nginx
    ports:
      - 8080:80
    depends_on:
      - frontend
      - backend
    volumes:
      - ./production/proxy.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongo-data:
